App\Domain\Travel\Model\Travel:
    type: entity
    table: travel
    id:
        id:
            type: TravelId

    fields:
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            groups: ['elastica']
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            groups: ['elastica']
            column: updated_at
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            groups: ['elastica']
            precision: 0
        slug:
           type: string
           length: 500
           groups: ['elastica']
           gedmo:
              translatable: {}
              slug:
                separator: -
                fields:
                   - title
        photo:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            groups: ['elastica']
            precision: 0
        startAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            groups: ['elastica']
            precision: 0
            column: start_at
        endAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            groups: ['elastica']
            column: end_at
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            groups: ['elastica']
            precision: 0
        stars:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            groups: ['elastica']
            precision: 0
        watch:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            groups: ['elastica']
            precision: 0
        status:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            groups: ['elastica']
            precision: 0
    embedded:
        geoLocation:
            class: App\Domain\Travel\ValueObject\GeoLocation
            columnPrefix: false
    manyToOne:
        user:
            targetEntity: App\Domain\User\Model\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: travel
            max_depth: 1
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        location:
            targetEntity: App\Domain\Location\Model\Location
            cascade:
                - persist
            fetch: LAZY
            mappedBy: travel
            inversedBy: null
            orphanRemoval: false
            max_depth: 1
            orderBy: null
        gpx:
            targetEntity: App\Domain\Gpx\Model\Gpx
            cascade:
                - persist
            fetch: LAZY
            mappedBy: travel
            inversedBy: null
            orphanRemoval: false
            max_depth: 1
            orderBy: null
    manyToMany:
        sharedusers:
            targetEntity: App\Domain\User\Model\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: travelsshared
            inversedBy: null
            max_depth: 1
            joinTable: {  }
            orderBy: null
