parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
        types:
            TravelId: App\Infrastructure\TravelBundle\Doctrine\Types\DoctrineTraveIdType
            LocationId: App\Infrastructure\LocationBundle\Doctrine\Types\DoctrineLocationIdType
            UserId: App\Infrastructure\UserBundle\Doctrine\Types\DoctrineUserIdType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Travel:
                type: xml
                prefix: App\Domain\Travel\Model
                dir: '%kernel.project_dir%/src/Infrastructure/TravelBundle/Resources/config/persistence/Model'
                is_bundle: false
            Gpx:
                type: xml
                prefix: App\Domain\Gpx\Model
                dir: '%kernel.project_dir%/src/Infrastructure/GpxBundle/Resources/config/persistence'
                is_bundle: false
            Images:
                type: xml
                prefix: App\Domain\Images\Model
                dir: '%kernel.project_dir%/src/Infrastructure/ImagesBundle/Resources/config/persistence'
                is_bundle: false
            Location:
                type: xml
                prefix: App\Domain\Location\Model
                dir: '%kernel.project_dir%/src/Infrastructure/LocationBundle/Resources/config/persistence'
                is_bundle: false
            Mark:
                type: xml
                prefix: App\Domain\Mark\Model
                dir: '%kernel.project_dir%/src/Infrastructure/MarkBundle/Resources/config/persistence'
                is_bundle: false
            Note:
                type: xml
                prefix: App\Domain\Note\Model
                dir: '%kernel.project_dir%/src/Infrastructure/NoteBundle/Resources/config/persistence'
                is_bundle: false
            TypeLocation:
                type: xml
                prefix: App\Domain\TypeLocation\Model
                dir: '%kernel.project_dir%/src/Infrastructure/TypeLocationBundle/Resources/config/persistence'
                is_bundle: false
            GeoLocation:
                type: xml
                prefix: App\Domain\Travel\ValueObject
                dir: '%kernel.project_dir%/src/Infrastructure/TravelBundle/Resources/config/persistence/ValueObject'
                is_bundle: false
            User:
                type: xml
                prefix: App\Domain\User\Model
                dir: '%kernel.project_dir%/src/Infrastructure/UserBundle/Resources/config/persistence'
                is_bundle: false
            StoredEvent:
                type: xml
                prefix: App\Domain\Event\Model
                dir: '%kernel.project_dir%/src/Infrastructure/EventBundle/Resources/config/persistence'
                is_bundle: false
            Budget:
                type: xml
                prefix: App\Domain\Budget\Model
                dir: '%kernel.project_dir%/src/Infrastructure/BudgetBundle/Resources/config/persistence'
                is_bundle: false
            TravelClone:
                type: xml
                prefix: App\Domain\TravelClone\Model
                dir: '%kernel.project_dir%/src/Infrastructure/TravelCloneBundle/Resources/config/persistence'
                is_bundle: false
