parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Travel:
               type: yml
               prefix: App\Domain\Travel\Model
               dir: '%kernel.root_dir%/../src/Infrastructure/TravelBundle/Resources/config/persistence'
               is_bundle: false
            Gpx:
                type: yml
                prefix: App\Domain\Gpx\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/GpxBundle/Resources/config/persistence'
                is_bundle: false
            Images:
                type: yml
                prefix: App\Domain\Images\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/ImagesBundle/Resources/config/persistence'
                is_bundle: false
            Location:
                type: yml
                prefix: App\Domain\Location\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/LocationBundle/Resources/config/persistence'
                is_bundle: false
            Mark:
                type: yml
                prefix: App\Domain\Mark\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/MarkBundle/Resources/config/persistence'
                is_bundle: false
            Note:
                type: yml
                prefix: App\Domain\Note\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/NoteBundle/Resources/config/persistence'
                is_bundle: false
            TypeLocation:
                type: yml
                prefix: App\Domain\TypeLocation\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/TypeLocationBundle/Resources/config/persistence'
                is_bundle: false
            User:
                type: yml
                prefix: App\Domain\User\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/UserBundle/Resources/config/persistence'
                is_bundle: false
            StoredEvent:
                type: yml
                prefix: App\Domain\Event\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/EventBundle/Resources/config/persistence'
                is_bundle: false

