# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(string:ELASTICSEARCH_HOST)%', port: '%env(int:ELASTICSEARCH_PORT)%' }
    indexes:
        travel:
            types:
                travel:
                    properties:
                        id:
                            type: text
                        createdAt:
                            type: date
                            format: 'yyyy-MM-dd HH:mm:ss'
                        updatedAt:
                            type: date
                        title:
                            type: text
                        slug:
                            type: text
                        photo: ~
                        startAt:
                            type: date
                        endAt:
                            type: date
                        description:
                            type: text
                        publishedAt:
                            type: date
                        stars:
                            type: integer
                        watch:
                            type: integer
                        status: ~
                        geolocation:
                            type: geo_point
                    persistence:
                        driver: orm
                        model: App\Infrastructure\TravelBundle\Resources\config\persistence\Model\Travel.orm.yml
                        provider: ~
                        listener:
                            insert: false
                            update: false
                            delete: false
                        finder: ~