framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
                    - App\Infrastructure\Middleware\DomainEventsMiddleware
            query.bus: ~
