tactician:
  commandbus:
    default:
      middleware:
        - tactician.middleware.locking
        - tactician.middleware.doctrine
        - tactician.middleware.domainEventStore
        - tactician.middleware.command_handler