<?php

namespace App\Tests\Domain\Location\Events;

use App\Domain\Location\Events\LocationWasRemoved;
use PHPUnit\Framework\TestCase;

class LocationWasRemovedTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testOcurredOn(): void
    {
        $locationId = mt_rand();
        $userId = mt_rand();
        $travelId = mt_rand();

        $locationWasRemoved = new LocationWasRemoved(
            $locationId,
            $userId,
            $travelId
        );
        $this->assertInstanceOf(\DateTime::class, $locationWasRemoved->occurredOn());
    }
}
