App\Domain\Mark\Model\Mark:
    type: entity
    table: mark
    id:
        id:
            type: string
            length: 150
            unique: true
            nullable: false
            id: true
    fields:
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        json:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: description
    embedded:
        geoLocation:
            class: App\Domain\Travel\ValueObject\GeoLocation
            columnPrefix: false
    lifecycleCallbacks: {  }
