App\Domain\Mark\Model\Mark:
    type: entity
    table: mark
    id:
        id:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        json:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: description
    embedded:
        geoLocation:
            class: App\Domain\Travel\ValueObject\GeoLocation
            columnPrefix: false
    oneToMany:
        location:
            targetEntity: App\Domain\Location\Model\Location
            cascade: {  }
            fetch: LAZY
            mappedBy: mark
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
