<?php

namespace App\Tests\UI;

use PHPUnit\Framework\TestCase;

class GetLocationsAPIControllerTest extends TestCase
{
    private $endPoint;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->endPoint = 'http://localhost/planing_travels/public/index.php';
    }

    public function testGetLocationsByTravel()
    {
        $client = new \GuzzleHttp\Client();

        $response = $client->request('GET', $this->endPoint.'/api/travel/2/locations', []);
        $this->assertEquals(200, $response->getStatusCode());
    }
}
