App\Domain\User\Model\PasswordResetToken:
    type: entity
    table: password_reset_tokens
    repositoryClass: App\Infrastructure\UserBundle\Repository\DoctrinePasswordResetTokenRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tokenHash:
            type: string
            length: 64
            nullable: false
            unique: true
            column: token_hash
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        expiresAt:
            type: datetime
            nullable: false
            column: expires_at
        usedAt:
            type: datetime
            nullable: true
            column: used_at
    manyToOne:
        user:
            targetEntity: App\Domain\User\Model\User
            inversedBy: null
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

