App\Domain\Gpx\Model\Gpx:
    type: entity
    table: gpx
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255
            precision: 0
            scale: 0
            nullable: false
        description:
            type: string
            length: 255
            precision: 0
            scale: 0
            nullable: false
        filename:
            type: string
            length: 255
            precision: 0
            scale: 0
            nullable: false
        color:
            type: string
            length: 255
            precision: 0
            scale: 0
            nullable: false
        createdAt:
            type: datetime
            precision: 0
            scale: 0
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            precision: 0
            scale: 0
            nullable: false
            column: updated_at
    manyToOne:
        travel:
            targetEntity: App\Domain\Travel\Model\Travel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: gpx
            joinColumns:
                travel_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
