App\Domain\Event\Model\StoredEvent:
     type: entity
     table: event
     repositoryClass: Ddd\Infrastructure\Application\Notification\DoctrineEventStore
     id:
       eventId:
          type: integer
          column: event_id
          generator:
          strategy: AUTO
     fields:
        eventBody:
          column: event_body
          type: text
        typeName:
          column: type_name
          type: string
          length: 255
        occurredOn:
          column: occurred_on
          type: datetime