name: Test php project

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building image from dockerfile
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }}"

      - name: More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Install dependencies
        run: composer install --ignore-platform-reqs

      - name: Run tests
        run: php vendor/bin/phpunit


